import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          style={{
            borderBottom: "1px solid grey",
            marginBottom: "1rem",
            padding: "2rem",
          }}
        >
          <ul>
            <li>
              <Link href="/static-render">Static Render</Link>
            </li>
            <ul style={{ marginLeft: "1rem" }}>
              <li>
                <Link href="/static-render/time-based-revalidation">
                  Time based revalidation
                </Link>
              </li>
              <li>
                <Link href="/static-render/route-revalidation">
                  Route revalidation
                </Link>
              </li>
              <li>
                <Link href="/static-render/on-demand-revalidation">
                  On-demand revalidation
                </Link>
              </li>
            </ul>
            <li>
              <Link href="/dynamic-render?city=Warsaw">Dynamic Render</Link>
            </li>
          </ul>
        </div>
        <div style={{ padding: "2rem" }}>{children}</div>
      </body>
    </html>
  );
}
